#!/usr/bin/env python3
"""Generate the compiled DAPHNE-board telemetry catalog from tag_list.csv.

Interface2 remains the source of truth. This generator selects read-only values
whose normal producer is the DAPHNE board service, expands the controlled NP04
HD inventory, and leaves {BoardId} for runtime substitution.
"""

from __future__ import annotations

import argparse
import csv
import itertools
import re
from pathlib import Path


NODE_PREFIX = "nsu=urn:dune:pds:daphne;s="
EXTERNAL_SUBSYSTEMS = {"Authority", "Endpoint Status", "OPC-UA Bridge"}
INSTANCES = {
    "Afe": [str(value) for value in range(5)],
    "Channel": [str(value) for value in range(40)],
    "Fan": [str(value) for value in range(2)],
    "Interface": ["eth0"],
    "DataLink": [str(value) for value in range(4)],
    "Sfp": ["timing", "ccm", "data0", "data1", "data2", "data3"],
    "Bus": ["1", "2"],
    "Address": [
        "0x10", "0x17", "0x12", "0x16", "0x32", "0x36", "0x70", "0x71", "0x72"
    ],
    "Device": ["spidev3.0"],
    "Rail": ["3VD3", "2VA1", "3VA6", "1VD8"],
    "Sensor": ["soc", "carrier"],
    "Service": [
        "firmware.service",
        "clockchip.service",
        "endpoint.service",
        "hermes.service",
        "daphne.service",
        "daphne-boot-ok.service",
        "rpu",
    ],
}
I2C_DEVICES = [
    ("1", "0x10"),
    ("1", "0x17"),
    ("2", "0x12"),
    ("2", "0x16"),
    ("2", "0x32"),
    ("2", "0x36"),
    ("2", "0x70"),
    ("2", "0x71"),
    ("2", "0x72"),
]
VALUE_TYPES = {"Boolean", "Integer", "Long", "Double", "String", "DateTime"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("tag_list", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--expected", type=int)
    return parser.parse_args()


def source_from_notes(notes: str) -> str:
    match = re.search(r"(?:^| \| )SOURCE=([^|]+)", notes)
    return match.group(1).strip() if match else "Interface2 proposed-v8 registry"


def expand_node_id(pattern: str) -> list[str]:
    if not pattern.startswith(NODE_PREFIX):
        raise ValueError(f"NodeId outside canonical namespace: {pattern}")
    node_id = pattern[len(NODE_PREFIX) :]
    placeholders = list(dict.fromkeys(re.findall(r"\{([^{}]+)\}", node_id)))
    if "BoardId" not in placeholders:
        raise ValueError(f"NodeId lacks {{BoardId}}: {pattern}")
    placeholders.remove("BoardId")

    if "Bus" in placeholders and "Address" in placeholders:
        placeholders.remove("Bus")
        placeholders.remove("Address")
        seeds = [
            node_id.replace("{Bus}", bus).replace("{Address}", address)
            for bus, address in I2C_DEVICES
        ]
    else:
        seeds = [node_id]

    result: list[str] = []
    choices = [INSTANCES.get(name) for name in placeholders]
    missing = [name for name, values in zip(placeholders, choices) if not values]
    if missing:
        raise ValueError(f"No controlled instances for {missing}: {pattern}")
    combinations = list(itertools.product(*choices)) if choices else [()]
    for seed in seeds:
        for values in combinations:
            expanded = seed
            for name, value in zip(placeholders, values):
                expanded = expanded.replace("{" + name + "}", value)
            result.append(expanded)
    return result


def cpp(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    args = parse_args()
    with args.tag_list.open(newline="", encoding="utf-8-sig") as stream:
        rows = list(csv.DictReader(stream))

    entries: list[tuple[str, str, str, str]] = []
    seen: set[str] = set()
    selected_patterns = 0
    for row in rows:
        if row["DCS Access"] != "Read-Only" or row["Subsystem"] in EXTERNAL_SUBSYSTEMS:
            continue
        value_type = row["Data Type"]
        if value_type not in VALUE_TYPES:
            raise ValueError(f"Unsupported value type: {value_type}")
        selected_patterns += 1
        for node_id in expand_node_id(row["OPC-UA Node Address"]):
            if node_id in seen:
                raise ValueError(f"Duplicate expanded NodeId: {node_id}")
            seen.add(node_id)
            entries.append(
                (
                    node_id,
                    value_type,
                    row["Eng Units"],
                    source_from_notes(row["Notes"]),
                )
            )

    if args.expected is not None and len(entries) != args.expected:
        raise ValueError(f"Expected {args.expected} expanded points, got {len(entries)}")

    lines = [
        "// Generated by scripts/generate_v8_telemetry_catalog.py; do not edit manually.",
        f"// Source patterns: {selected_patterns}; expanded HD-board points: {len(entries)}.",
    ]
    for node_id, value_type, unit, source in entries:
        lines.append(
            f'{{"{cpp(node_id)}", CatalogValueType::{value_type}, '
            f'"{cpp(unit)}", "{cpp(source)}"}},'
        )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"patterns={selected_patterns} expanded_points={len(entries)} output={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
